Repository JuliaDynamics/ComplexityMeasures.jl, pull requests merged in 2022-12, with the labels that each got.

#177 Encoding for binnings
  .DS_Store
  Project.toml
  docs/.DS_Store
  docs/src/devdocs.md
  src/Entropies.jl
  src/encoding/all_encodings.jl
  src/encoding/outcomes.jl
  src/encodings.jl
  src/probabilities.jl
  src/probabilities_estimators/histograms/rectangular_binning.jl
  src/probabilities_estimators/histograms/value_histogram.jl
  test/Project.toml
  test/probabilities/estimators/permutation.jl
  test/probabilities/estimators/transfer_operator.jl
  test/probabilities/estimators/value_histogram.jl
  test/utils/encoding.jl
Labels: enhancement, binning

#132 Multiscale analysis
  .gitignore
  docs/make.jl
  docs/src/multiscale.md
  src/Entropies.jl
  src/multiscale.jl
  src/multiscale/composite.jl
  src/multiscale/regular.jl
  test/multiscale/Composite.jl
  test/multiscale/Regular.jl
  test/multiscale/downsampling.jl
  test/multiscale/multiscale.jl
  test/runtests.jl
Labels: enhancement, new method, discussion-design, hacktoberfest-accepted

#191 Clarify dicsrete vs. differential estimators
  docs/src/entropies.md
  docs/src/examples.md
  docs/src/index.md
  docs/src/probabilities.md
  src/entropies/estimators/nearest_neighbors/KozachenkoLeonenko.jl
  src/entropies/estimators/nearest_neighbors/Kraskov.jl
  src/entropies/estimators/nearest_neighbors/Zhu.jl
  src/entropies/estimators/nearest_neighbors/ZhuSingh.jl
  src/entropies/estimators/order_statistics/AlizadehArghami.jl
  src/entropies/estimators/order_statistics/Correa.jl
  src/entropies/estimators/order_statistics/Ebrahimi.jl
  src/entropies/estimators/order_statistics/Vasicek.jl
  src/entropy.jl
Labels: documentation

#207 Simplify `SymbolicPermutation` source code
  docs/src/entropies.md
  src/probabilities_estimators/permutation_ordinal/SymbolicPermutation.jl
Labels: documentation, cleanup, symbolization

#211 Differential entropy estimators: various fixes
  CHANGELOG.md
  docs/src/entropies.md
  docs/src/examples.md
  src/entropies/estimators/nearest_neighbors/KozachenkoLeonenko.jl
  src/entropies/estimators/nearest_neighbors/Kraskov.jl
  src/entropies/estimators/nearest_neighbors/Zhu.jl
  src/entropies/estimators/nearest_neighbors/ZhuSingh.jl
  src/entropies/estimators/order_statistics/AlizadehArghami.jl
  src/entropies/estimators/order_statistics/Correa.jl
  src/entropies/estimators/order_statistics/Ebrahimi.jl
  src/entropies/estimators/order_statistics/Vasicek.jl
  src/entropy.jl
  test/entropies/estimators/alizadeharghami.jl
  test/entropies/estimators/correa.jl
  test/entropies/estimators/ebrahimi.jl
  test/entropies/estimators/kozachenkoleonenko.jl
  test/entropies/estimators/kraskov.jl
  test/entropies/estimators/vasicek.jl
  test/entropies/estimators/zhu.jl
  test/entropies/estimators/zhusingh.jl
Labels: bug, documentation, tests, code-clarity, cleanup

#212 Documentation fixes
  docs/src/entropies.md
Labels: documentation

#230 Goria (2005) differential entropy estimator
  docs/src/entropies.md
  docs/src/examples.md
  src/entropies_estimators/nearest_neighbors/Goria.jl
  src/entropies_estimators/nearest_neighbors/nearest_neighbors.jl
  test/entropies/estimators/estimators.jl
  test/entropies/estimators/goria.jl
Labels: enhancement, new differential entropy estimator
